# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1omontc41d4dH2AD8-dk5GZ1yojb5CG6u
"""

#punto_1 

import numpy as np
import matplotlib.pyplot as plt

class EmanuelClass:
    def __init__(self, size, fill_type, num_matrices):
        self.size = size
        self.fill_type = fill_type
        self.num_matrices = num_matrices
        self.matrices = []

    def matrices(self):
        for _ in range(self.num_matrices):
            if self.fill_type == "zeros":
                matrix = np.zeros(self.size)
            elif self.fill_type == "ones":
                matrix = np.ones(self.size)
            elif self.fill_type == "random":
                matrix = np.random.uniform(20, 40, self.size)
            else:
                raise ValueError("Invalid fill_type")

            self.matrices.append(matrix)

    def multiplicacion(self):
        if self.num_matrices < 2:
            raise ValueError("Insufficient number of matrices for multiplication")

        mult = self.matrices[0]
        for i in range(1, self.num_matrices):
            mult = np.matmul(mult, self.matrices[i])

        return mult

    def imagen(self):
        if self.fill_type == "random":
            raise ValueError("Cannot display random matrices as images")

        for matrix in self.matrices:
            plt.imshow(matrix, cmap='gray')
            plt.show()

    def suma(self):
        total_sum = []
        for matrix in self.matrices:
            total_sum.append(np.sum(matrix))

        return total_sum

# punto_2

class clase:
    def __init__(self, nombre, edad):
        self.__Nombre = nombre
        self.__edad = edad

    def saludar(self):
        print(f"Hola,buenos dias,tardes o noches, soy {self.__Nombre} y tengo {self.__edad} años de edad.")